version: "3.4"
services:
  api:
    container_name: wcstore_cdn
    build:
      context: ../../..
      dockerfile: infrastructure/docker/java.dockerfile
      target: build
    env_file: 
      - .env